# Values used for the deployed application.
service:
  name: delivery-varnish
  # Apply the certificate from content test by default
  certificateAwsArn: "arn:aws:acm:eu-west-1:070529446553:certificate/53071112-759c-4875-97e2-c62425df1381"

elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=d"

s3:
  bucketName: "content-test-elb-access-logs-eu-west-1"
  prefix: "upp-dev-delivery-eu/delivery-varnish"
  enabled: false
